### ISSUE TITLE
Incorporate nested tags (feature request)

### ISSUE THREAD

**Issue by piersdd** [royxue/obsidian-things3-sync#13]
creating a synced Things task with a #P/Kim tag, fails to create that task in Things,
even though within Things, the Tags, P exists, as does it's child Kim.

**Comment by royxue** [comment]
@piersdd 
I was thinking this might caused by the things3 api, because the way how to create todo in things, is forming an api link, / may not work well there. 
I will go check this problem and reply later next week.

**Comment by piersdd** [comment]
***@***.*** 
<br/>I was thinking this might caused by the things3 api, because the way how to create todo in things, is forming an api link, / may not work well there. 
<br/>I will go check this problem and reply later next week.
<br/>
<br/>-- 
<br/>Reply to this email directly or view it on GitHub:
<br/>https://github.com/royxue/obsidian-things3-sync/issues/13#issuecomment-1666860881
<br/>You are receiving this because you were mentioned.
<br/>
<br/>Message ID: ***@***.***&gt;</div>
