### ISSUE TITLE
No link added to Obsidian document when using "Create Things Todo from Note"

### ISSUE THREAD

**Issue by lougreenwood** [royxue/obsidian-things3-sync#14]
I'm not sure whether this is expected behaviour, but if I try to create a Things todo from an Obsidian note everything works as expected on the Things side (i.e the todo is created, a backlink is also created), however the Obsidian note does not get updated with a link to the Things todo.

I found this existing issue, but it's not clear to me if this is talking about creating a note from text or for the whole note.

Is this feature supported?

Thanks!! 🙇

**Comment by royxue** [comment]
@lougreenwood 
Hi, thanks for reaching out.
Currently the plugin only supports for creating a todo from a line of text, it will create a backlink and insert in obsidian.
It's not working with the whole note or the title for now

**Comment by royxue** [comment]
@lougreenwood 
do you have any further updates? 
I will wait few days, if no replied, I will close the issue. thx ;)

**Comment by lougreenwood** [comment]
Thanks @royxue.

You said the following: 
> It's not working with the whole note or the title for now

Should I infer from this that means adding backlinks to whole notes is planned? If so maybe you could keep this issue open or open a new issue so track progress and help other people looking for the same feature?

🙇‍♂️

**Comment by royxue** [comment]
@lougreenwood 
Honestly speaking, I'm not sure about it. I think Obsidian didnt allow add link to the note title...so it's impossible to do that
![image](https://github.com/royxue/obsidian-things3-sync/assets/4725561/7bbb2b7f-91d9-42c9-a082-44b7ba51694e)

**Comment by lougreenwood** [comment]
I'm not sure we'd need it in the title, I certainly didn't expect it to populate the title.

For me, prepending it to the note on the first line of the file would be better than nothing. Once a user has the link in the note they can move it to the correct place in the file.

Maybe even adding to the note "properties" could be useful so it's stored as consistent metadata?

**Comment by royxue** [comment]
@lougreenwood 
Adding to the first line, this just sounds like a customized feature, not everyone gonna like it. However I think maybe you can implement this in your local plugin code, it could work.

About properties this might be a good solution, but it gonna need some time to consider about it. Cuz it's a new feature in obsidian, previous version compatibility should be taken carefully

**Comment by lougreenwood** [comment]
> About properties this might be a good solution, but it gonna need some time to consider about it. Cuz it's a new feature in obsidian, previous version compatibility should be taken carefully

Since there's currently no support for link a note to a things task then I'm not sure you need to be concerned about backwards compatibility or breaking changes for this feature.

So using `file properties` to store a link to `Things Task` for full notes just would require a minimum version of Obsidian which supports properties. If people want the feature, they'll need to update their version of Obsidian - that seems reasonable to me.
