### ISSUE TITLE
Feature Request: Do not link the To-Do

### ISSUE THREAD

**Issue by pwntester** [royxue/obsidian-things3-sync#15]
First of all, thanks a lot for the plugin! Im using it mostly to create To-Dos from my meeting note's action items (not Todos `[ ]` but just bullet points `- `). This is working fine but after creating the ToDo in Things, it updates the Meeting note to add a link to the Things's ToDo. I guess this is used when you want to sync the ToDos and toggle their status from either app. In my case, I just want to create the ToDo in Things and handle it there which I think it may be a common use case. 

Would it be possible to add an option to not add links to the Obsidian note? (Im fine keeping the link back to obsidian in the Things's ToDo although I guess it would be nice to have another config setting to not add those links either)

Thanks!

**Comment by royxue** [comment]
@pwntester 
Hi, thanks for the issue.
It's possible to remove the link, but if without link, you cannot complete todo in Obsidian and sync the status to things3 anymore.

I'll consider about this feature, but maybe we should have something like compact mode in the plugin

**Comment by pwntester** [comment]
Thanks for considering it, it would be great to have a "detached" mode

**Comment by royxue** [comment]
@pwntester 
Sorry for late reply, finally have some time making new release, I gonna include this feature in the new version. Thanks again for creating this issue.
