### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by dad-hh** [royxue/obsidian-things3-sync#18]
many thanks for the plugin, unfortunately it cannot be installed.
Error message: plugin ID mismatch

Obsidian Version 1.5.3 (Installer 1.5.3)

What is the solution?

Thank you very much

**Comment by royxue** [comment]
@dad-hh 
this may caused by the new naming requirements as in #17 
I will check the changes, and maybe release a new version to solve the problem.
Thx for submit this issue

**Comment by royxue** [comment]
@dad-hh 
Now the new version could work properly, you can just update the latest version

**Comment by dad-hh** [comment]
thanks for the quick solution, everything ok
