### ISSUE TITLE
Text after '&' is truncated

### ISSUE THREAD

**Issue by michielschok** [royxue/obsidian-things3-sync#19]
If an "&" is present in the line of text in the to-do, the to-do is truncated in Things.

So, If I have a line in Obsidian that reads
`Create a mail for Alice & Bob regarding crypto`

The corresponding things to-do would read 
`Create a mail for Alice`

**Comment by royxue** [comment]
@michielschok 
this is because the way how to make an TODO in things3 is through an URL, where & is a special mark there. So that it cannot parse this as a whole sentence

**Comment by michielschok** [comment]
Would a replacement of “&” with “%26” do the trick?

if I follow the prompts at https://culturedcode.com/things/support/articles/2803573/ it construct an url like 
`things:///add?title=Create%20a%20mail%20for%20Alice%20%26%20Bob%20regarding%20crypto`

And that seems to work.

**Comment by royxue** [comment]
@michielschok oh yeah, it could work
do you mind submit a pull request about this?

**Comment by royxue** [comment]
@michielschok 
Hey, Sorry for disturbing.
I am going to make a new release of this plugin, just wanna check whether if you are interested submit a PR of this issue. If you are interested, please let me know, and I will include this feature within new version.

**Comment by michielschok** [comment]
No, unfortunately I don't have any time at hand to start learning about developing on obsidian plugins.

**Comment by royxue** [comment]
released in https://github.com/royxue/obsidian-things3-sync/releases/tag/1.3.0

**Comment by michielschok** [comment]
☕️
