### ISSUE TITLE
Sends the task to Things but 95% of the time doesn't create a link

### ISSUE THREAD

**Issue by huyz** [royxue/obsidian-things3-sync#2]
At some point I saw that the plugin was able to create a markdown link to the task in Things. But now for some reason, I can't get that link to appear. The task gets created in Things, but the current checklist item doesn't get wrapped in a markdown link.

Any ideas?

**Comment by royxue** [comment]
@huyz 
Could you share some screenshot(maybe) of the created todo in things?

By design, the created todo with be attached with a reference link back to the obsidian file.

**Comment by huyz** [comment]
![screenshot 2022-10-24T105935Z](https://user-images.githubusercontent.com/128394/197511304-d13a9b88-1264-4fdd-85a2-d80fe4132c89.png)
But no reference link in Obsidian: 
![screenshot 2022-10-24T105946Z](https://user-images.githubusercontent.com/128394/197511360-09347e46-a476-439d-9fcf-da5d5ce1aa86.png)

It's probably some conflict with another plugin, but no idea which (I don't use Obsidian Web like https://github.com/royxue/obsidian-things3-sync/issues/1).

I also use vim keybindings

**Comment by royxue** [comment]
@huyz 
Yep, current version of this plugin, only support create todo from text, it didnt support create from an existed obsidian todo now.

Sorry for the inconvenience.
I will add support of this feature from next release.

**Comment by huyz** [comment]
Oh, but when I try:
- text
- heading
- list item

it doesn't work either.

**Comment by royxue** [comment]
This is weird.
So the text could be transferred as an Obsidian todo, but without the link?

**Comment by huyz** [comment]
Yeah.  I was able to get a link once or twice.  But now I can't get one no matter what I do.  Restarting Obsidian didn't help.

**Comment by royxue** [comment]
I tried to reproduce your situation, but it seems always work for me.
could you help trying reinstall the plugin, like remove the folder in /plugins, and copy a new one there

**Comment by royxue** [comment]
@huyz did you still face this problem?

**Comment by huyz** [comment]
@royxue Yes it's still happening.  But I just tried in the sandbox and it works on a text line. So it must be a conflict with one of many other plugins.  I need to test further

**Comment by huyz** [comment]
The no-longer-supported plugin https://github.com/gavinmn/obsidian-things-link doesn't have that conflict problem.  Also it works whether text, heading, or list item.  Maybe you could check out their code and see how they do it?

I prefer your plugin because it can actually sync the toggle.

**Comment by royxue** [comment]
could you help try replace this main.js, if it has conflicts with other plugins, I think maybe caused by the protocolHandler name

[main.js.zip](https://github.com/royxue/obsidian-things3-sync/files/9895446/main.js.zip)

**Comment by royxue** [comment]
@huyz 
Just add a new release as 1.0.2
Could you try that version

**Comment by huyz** [comment]
Yes! it mostly works now.  There may be other issues, but I'll file separate ones...
