### ISSUE TITLE
About capture date

### ISSUE THREAD

**Issue by schinie** [royxue/obsidian-things3-sync#20]
Hi, can I set date and due date for my single task? I found the “when” date can be captured only if my filename is a date such as “2024-03-13”

**Comment by royxue** [comment]
@schinie 
Hi, yes, currently the date capture func is designed to be used with daily notes. When inline date capture is on plan, but I was kinda occupied recently.
If you are interesting, pull request is always welcome.

**Comment by royxue** [comment]
@schinie 
Hey, Sorry for disturbing.
I am going to make a new release of this plugin, just wanna check whether if you are interested submit a PR of this issue. If you are interested, please let me know, and I will include this feature within new version.

**Comment by royxue** [comment]
released in https://github.com/royxue/obsidian-things3-sync/releases/tag/1.3.0
