### ISSUE TITLE
tags not syncing

### ISSUE THREAD

**Issue by chump** [royxue/obsidian-things3-sync#4]
I love that this plugin exists. An issue I have is that the tags aren't carrying over (Even though they exist within Things). 

I also noticed that if I try tagging it shows up in 'inbox', and if I have no tags it goes to the Today view - is this intentional? I think it's more effective to have everything go straight to the Things inbox. 

I notice that once you create a task, it auto generates the next task checkbox, which is fantastic, but I can't highlight all the tasks and send them over to Things. I still need to highlight or be on the specific task line to have it sync over.

**Comment by royxue** [comment]
@chump 
hi, glad you like it.
for the tag, I will go have a check with that.

as for Inbox or Today, the plugin will read the file title, if it's a daily journal, it reads the date, and mark it in Things, so if it's a todo in today's note, it will be in Today, on other situations, it will be in Inbox.

**Comment by royxue** [comment]
@chump also, I was thinking about sync multiple lines of tasks earlier, do you think this would a very frequent action?

**Comment by chump** [comment]
Hi @royxue I was doing all of my things/obsidian testing in a daily note - And I just tested it out again, with a tag it's going to inbox, without it's going to today. 

In terms of syncing multiple lines it would definitely be far more efficient if i've got several tasks and I don't need to click on each one and run the command multiple times.

**Comment by royxue** [comment]
@chump thx, I found there is a bug when creating the todo with tag, I gonna fix this later.

**Comment by royxue** [comment]
@chump try with this new version 1.0.3, the tags bug should be fixed now.
https://github.com/royxue/obsidian-things3-sync/releases/tag/1.0.3

**Comment by royxue** [comment]
@chump 
follow up, is your problem solved?
