### ISSUE TITLE
@chump also, I was thinking about sync multiple lines of tasks earlier, do you think this would a very frequent action?

### ISSUE THREAD

**Issue by ghost** [royxue/obsidian-things3-sync#5]
@chump also, I was thinking about sync multiple lines of tasks earlier, do you think this would a very frequent action?

Just as a comment: yes - that would be great, I have loads of tasks, which I want to transfer but even with a hotkey it is a bit of work that I have not done yet.

**Comment by royxue** [comment]
@svenschuldt kk will add this feature in the next release.

**Comment by royxue** [comment]
@svenschuldt 
I did some research about this feature, I think this might be hard to implement. as the communication between things and obsidian is lacking of some information, which would lead replacing text in obsidian became a mess.
