### ISSUE TITLE
Subject line of Obsidian note is not transferred to Things addendum. 

### ISSUE THREAD

**Issue by guennt** [royxue/obsidian-things3-sync#6]
Hello, 

Thanks for this great plugin that makes organization more effective. 
The PlugIn works as far, as creating a Things task is concerned including referencing back to the Obsidian note.

**My problem:** 

When creating a Things-task on my Mac, the title of the Obsidian-note ( Headline) is not transferred to the Things-task.
The subject line in Things remains empty. 
This subject line must then always be entered manually. This is avoidable effort. 

**Question 1:** how can the subject line in the Things-task be filled in automatically. 

**Question 2**: I have tried to install the "obsidian-things3-sync" PlugIn also on my mobile devices. But this failed,
with the remark "this device is not supported". ( I am using an iPhone ME-second edition ) Is there really no "obsidian-things3-sync" for mobile apple devices ??

**Question 3:** is there a way that the content of the Obsidian note is also transferred to the things task. Or is this feature generally not provided. 

Thanks for feedback and have a happy new year 2023 
Geunkt

**Comment by royxue** [comment]
@guennt 
Hi, Geunkt
Glad to hear this plugin provide help for you.
as for your questions
1. For obsidian note title currently cannot be sync to things3, this feature is no implemented yet. 
2. This plugin in should be working on iOS, I tested it on iphone before. maybe you should check the Obsidian version(min version 0.15.0 is required)
3. So as I understand, what you want is note title as task title, and note content as task content, basically is make the whole osbidian note into a things3 task, am i right? I never think about this usage before, could you provide more description about the advantages of it? I will consider about this.

**Comment by guennt** [comment]
Hi royxue, 

Thanks royxue for your answer. 

to point 3) 
Yes, I meant it the way you describe it.
I have also thought about it again. I think to take the content of an obsidian-note into a Things3 task as content is not very useful. The reason I see is, that because of the linking I can access the content in the obsidian-note at any time from the Things task by clicking on the link. 
**Really important and useful would be that the Obsidian-note-title is taken over as Things-task-title. That would be a valuable contribution to simplifying the work.** 

As far as the plug-in under i.OS is concerned, it cannot be due to the version. I have the current version 16.2. I will try it again anyway and then report. 

I wish you a good and healthy year 2023. 

Geunnt

**Comment by royxue** [comment]
@guennt 
I will take this into consideration, I think this feature would be added in the next release. But I will need to thinking about details, as how to put things3 link in obsidian, apparently put that link in title would not be that good, maybe use YAML as metadata for the note.

For the mobile version, could you try install with the latest 1.1.0 version. it seems last release 1.0.3 has some bugs which cannot be installed correctly.

**Comment by guennt** [comment]
Hello royxue,

Thank you for your quick reply. My comments on this: 

1. **i chose version 1.1. on mobile devices** and it actually works.
Thank you very much for that. Now the PlugIn is even more valuable and time saving as it works on all devices ( mobile + Mac ). 

2. **I was pleased** to see your willingness to organize the automatic transfer of the Obsidian Note title to the Things-task ( title line ). This would also be a further progress. 
3. **shortcut topic**: In the PlugIn description, there is a + sign next to the tool icon. With this I can set up short-cuts. However, I have problems with it on mobile devices. I do not succeed in a short cut, because no keyboard appears at this point. Do you have an idea ?  ( see screenshot ) 
4. **DATE function**: The Plug-In description contains a statement about DATE " syncing between Obsidian and Things3 supporting Mulit-Language, tags **and date.** The practical application does not succeed for me. What is meant with it concretely. Can a current date from Obsidianbe transferred to Things3 ?
5. **CLICK to UPDATES** failed. ( pls screenshot ) I have no explanation that the error " failed to load community plugins" appears, although the device is clearly online. 
6. can I read somewhere what are the main changes in the new version 1.1. compared to the previous version 1.03 ?  

I hope this wasn't too much of an issue. Maybe you can still give me some feedback. I would be grateful for it.
I wish you a nice weekend.

Geunnt

![IMG_0009](https://user-images.githubusercontent.com/121873100/210803571-eb3d25d0-a3ce-495a-a625-b171bce1f136.jpeg)


![IMG_0830](https://user-images.githubusercontent.com/121873100/210803797-60aa8ed7-dd70-419a-a820-75ee59652a1a.jpeg)

**Comment by royxue** [comment]
@guennt 
Glad that the new version works for you.

3. i never tried shortcut on mobile before, actually Im not sure whether obsidian shortcut would work for mobile or not. Maybe you can try with other plugin, if shortcut works with them, it should work here.

4. The DATE function  **only** work for daily note, it will automatically read the daily title(which include a date) and put it into todo date. For other format of date, currently is not supported.

5. Im not quite sure, but this seems to be an obsidian problem, maybe leave a question in their forum.

6. there is [changelog](https://github.com/royxue/obsidian-things3-sync/blob/master/changelog) in the repo, also there is some [release notes](https://github.com/royxue/obsidian-things3-sync/releases). You can find latest changes there.

Feel free to give me feedbacks! Your suggestion is making this plugin better!

**Comment by guennt** [comment]
Thanks royxue for your answer. 
You have helped me, to see something clearer. Concerning point 5, I will post a question in the obsidian forum. 

Best regards
Geunkt

**Comment by royxue** [comment]
@guennt 
OK！
I gonna close this issue.
The title to todo function should be in the next release. I think it might be in Feb, because recently there will be the Chinese lunar new year vacation.

**Comment by royxue** [comment]
@guennt 
Try with this [new release](https://github.com/royxue/obsidian-things3-sync/releases/tag/1.2.0)
Now you can create todo from a note
