### ISSUE TITLE
Obsidian URL seems to be wrong!

### ISSUE THREAD

**Issue by davebhc71** [royxue/obsidian-things3-sync#8]
See the attached PNG. I’m thinking the URL is being created incorrectly by the Plugin. There is a space between the App link and the Note section. The Vault Name is iPad Air, so should it be written “iPad **%20** Air” in the URL?
![CDCA3E63-63A6-4C6E-B73C-9EC6BDEAB205](https://user-images.githubusercontent.com/80698092/215336180-ffd50c69-9358-473a-9289-fe6288daa311.jpeg)

**Comment by royxue** [comment]
@davebhc71 
Thanks for submit this bug.
It seems obsidian api didnt process the vault name with a space, I will handle this. and release the fix asap

**Comment by royxue** [comment]
@davebhc71 
Fixed in the latest 1.2.1.
You can update the plugin and go have a try, thanks.

**Comment by davebhc71** [comment]
Thanks! That did it!On Jan 29, 2023, at 8:41 PM, Roy Xue ***@***.***> wrote:﻿
@davebhc71
Fixed in the latest 1.2.1.
You can update the plugin and go have a try, thanks.
