### ISSUE TITLE
Syntax of link in the note

### ISSUE THREAD

**Issue by abdcef** [royxue/obsidian-things3-sync#9]
Thanks for making this plugin!
I was wondering if it is possible to have the syntax in the note as: 
This is my todo → [things](things URL)

**Comment by royxue** [comment]
@abdcef 
Sorry, I think I didnt get your issue clearly.

I think for now, this plugin do use this  syntax [things](things URL), which is the basic format of markdown links, am i right?

**Comment by abdcef** [comment]
Sorry, I missed responding to your feedback.

My requested syntax is as follows:

Current:
`- [ ] [This is a task](things URL)`

Requested:
`- [>] This is a task → [things](things URL)`

The current format messes up the task if it starts with a tag. Also, I prefer indicating that the particular task has been transferred to things.

**Comment by royxue** [comment]
Hi,

Im not sure if this will be a common usage, so I wont change this if no other people request for this.

But I think if you want it to make it this way, you can modify my code, and compile it for a special version, just put it in your obsidian folder it will work.

Best
